name: Deploy to GAE

on:
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_APP_ENV: PROD
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          file_name: .env
      - name: Deploy to App Engine
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy
        uses: google-github-actions/deploy-appengine@v0

